---
title: "09-16-Recipes"
description: |
  Analysis of Allrecipes data from TidyTuesday
  
   The data comes from the tastyR package (a dataset assembled from Allrecipes.com) and was prepared for analysis in R.
author: "Timeo Coletta"
date: September 16, 2025
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
editor: visual
execute:
  warning: false
  message: false
---

**Sources:**

<a href = "https://cran.r-project.org/web/packages/tastyR/index.html" target = "_blank" > Allrecipes </a>

<a href = "https://github.com/hardin47/TidyTuesday/tree/gh-pages/2025-09-16" target = "_blank" > Tidy Tuesday Data</a>

```{r}
library(tidyverse)
library(DT)
library(fontawesome)
fontawesome::fa_html_dependency()
```

```{r}
all_recipes <- readr::read_csv ('https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-09-16/all_recipes.csv')
cuisines <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-16/cuisines.csv') |> 
  mutate(name_link = paste0('<a href = "',url,'">',name,'</a>')) |> 
  rename(cuisine = country) |> 
  mutate(full = floor(avg_rating + 0.25),
         half = ifelse((avg_rating + 0.25 - full) >= 0.5, 1, 0),
         empty = 5 - full - half) |> 
  mutate(stars = ifelse(is.na(avg_rating), NA,
                              paste0( 
    strrep('<span style="color: gold;">&#9733;</span>', full),   # ★
    strrep('<span style="color: gold;"><i class="fa-solid fa-star-half"></i></span>', half),    # optional placeholder for half
    strrep('<span style="color: lightgray;">&#9733;</span>', empty) # ☆ in grey
  
)))
```

```{r}
cuisines |> 
  select(name_link, stars, cuisine, calories, fat, carbs,
         protein, avg_rating, total_ratings, reviews,
         prep_time, cook_time, total_time, servings) |> 
  janitor::clean_names(case = "title") |> 
  DT::datatable(escape = FALSE,
                class = 'display',
                extensions = 'Buttons',
                rownames = FALSE,
                filter = 'top',
                options = list(
                  dom = 'Bfrtip',
                  buttons = list(
                    list(extend = 'colvis', 
                         text = 'select nutritional info',
                         columns = c(3:6)),
                    list(extend = 'colvis', 
                         text = 'select rating info',
                         columns = c(7:9)),                    
                    list(extend = 'colvis', 
                         text = 'select cook info',
                         columns = c(10:13))  
                    ),
                  columnDefs = list(list(visible = FALSE,
                                         targets = c(3:13)))
                ))
```
