project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Science Projects"
        menu: 
         - text: "Frogs in Australia Mapped"
           href: Frogs in Australia Mapped.html
         - text: "Mexican Passport Visa Rules"
           href: Mexican Passport Visa Rules.html
         - text: "Recipes Search Engine"
           href: Recipes Search Engine.html
         - text: "Netflix Age Ratings"
           href: Netflix Age Ratings.html
         - text: "Cat & Dog Adoptions"
           href: Cat & Dog Adoptions.html
         - text: "NY Taxi Anonymity Breach"
           href: NY Taxi Anonymity Breach.html
         - text: "Speeding Stops and Arrests"
           href: Speeding Stops and Arrests.html
      - text: "Economics Projects"
        menu: 
         - text: "Green Development Project"
           href: Green Development Project.html
         - text: "Monetary Policy Project"
           href: Monetary-Policy-Project.html
         - text: "Data Applied to Economics"
           href: Data Applied to Economics.html

format:
  html:
    theme:
      light: yeti
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
